apiVersion: apps/v1  # Deployment
kind: Deployment # Deployment
metadata:  # Deployment
  name: nginx-Deployment # Deployment
  labels: # Deployment
    app: nginx # Deployment
    type: production-grade # Deployment
spec:
  replicas: 3 # ReplicaSet
  selector: # ReplicaSet
    matchLabels:  #ReplicaSet
      app: nginx #ReplicaSet
  template: # Pod
    metadata:  # Pod
      labels: # Pod
        app: nginx # Pod
    spec:  # Pod
      containers: # Pod
      - name: nginx # Pod
        image: nginx:alpine # Pod
        ports: # Pod
        - containerPort: 80 # Pod

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app-development
  labels:
    app: deployment-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tour
  template:
    metadata:
      name: pod-level
      labels:
        app: deployment-app
    spec:
      containers:
      - name: nginx-dx
        image: nginx:1.25.3